[package]
name = "adventofcode"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.1"

[[bin]]
name = "1a"
path = "main.rs"

[[bin]]
name = "1b"
path = "b.rs"
